name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-22"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTBhYWRmNWMtZTRjZS00YjJlLTg4ODYtNWExZjNmMjJiMGU3IiwidGVuYW50X2lkIjoiMjY4Y2I2Yzk2MWRiMTg4NWJkZWNiODliYmZlZjdkYzgxYTljMjJlMTAwYTZlZWYzNmY5YWY5NzFhYzRiNzA0YiIsImludGVybmFsX3NlY3JldCI6IjQ3YzBiMzNjLWQ1ZTktNDRlZS05ZjMyLTJjYTNkNzZkOWVmOSJ9.La6H6U6xsrfvmL1EzkQ3IeCAgmgqHrFHzoxy759Khls"
JWT_SECRET="mysecretkey"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1